#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
    echo "Mandatory hostname not specified"
    exit 1
fi

source $(dirname $(realpath $0))/../config/global
source $(dirname $(realpath $0))/../scripts/colors

remote=${hostip[$1]}

echo "${yellow}- Installing base packages on $1/$remote ...${reset}"
set_dark

pkgs="${extra_packages[all]}  ${extra_packages[$1]}"
if [ -n "$pkgs" ]; then
    set_dark
    ssh root@$remote "apt-get install -y $pkgs && apt-get -y autoremove"
    reset_color
else
    echo "  - No packages defined."
fi
