#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
    echo "Mandatory hostname not specified"
    exit 1
fi

source $(dirname $(realpath $0))/../config/global
source $(dirname $(realpath $0))/../scripts/colors

remote=${hostip[$1]}

echo "${yellow}- Installing docker-compose …${reset}"
set_dark

if ssh root@$remote "command -v docker-compose" >/dev/null; then
    echo "Docker already installed: $(ssh root@$remote 'docker-compose --version')"
else
    ssh root@$remote "apt-cache search openssl"
    ssh root@$remote "apt-get install -y python3-pip python3-setuptools python3-dev libffi-dev libssl-dev gcc libc-dev make && apt-get -y autoremove"
    ssh root@$remote "pip3 install docker-compose"
fi

reset_color
