#!/usr/bin/env bash
set -e
if [ -z "$1" ]; then
    echo "Mandatory host name not specified"
    exit 1
fi

source $(dirname $(realpath $0))/../config/global
source $(dirname $(realpath $0))/../scripts/colors

templ=$workingdir/config/nginx/nginx-ds.conf
source $workingdir/scripts/mo

remote=${hostip[$1]}

echo "${yellow}- Installing nginx reverse proxy …${reset}"
set_dark

if ssh root@$remote "command -v nginx" 2> /dev/null; then
    echo "  - Nginx package already installed"
else
    ssh root@$remote "apt-get install -y nginx"
fi

export nginx_servername
export os_hostname
cat $templ | mo > $target/nginx-docspell

scp $target/nginx-docspell root@$remote:/etc/nginx/sites-available/docspell
ssh root@$remote "ln -snf /etc/nginx/sites-available/docspell /etc/nginx/sites-enabled/docspell"
ssh root@$remote "rm -f /etc/nginx/sites-enabled/default"
ssh root@$remote "systemctl reload nginx"
ssh root@$remote "nginx -t"

reset_color
