#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
    echo "Mandatory hostname not specified"
    exit 1
fi

source $(dirname $(realpath $0))/../config/global
source $(dirname $(realpath $0))/../scripts/colors

remote=${hostip[$1]}

echo "${yellow}- Installing unoconv service on $1/$remote ...${reset}"
set_dark

echo "  - Add systemd unit"
scp $workingdir/config/unoconv/systemd.unit root@$remote:/etc/systemd/system/unoconv.service
ssh root@$remote "systemctl enable unoconv.service"
ssh root@$remote "systemctl daemon-reload"

echo "  - Starting unoconv service"
ssh root@$remote "systemctl start unoconv"
