#!/usr/bin/env bash
set -e
if [ -z "$1" ]; then
    echo "Mandatory host name not specified"
    exit 1
fi

source $(dirname $(realpath $0))/../config/global
source $(dirname $(realpath $0))/../scripts/colors

templ=$workingdir/config/nginx/nginx-ds.conf
source $workingdir/scripts/mo

remote=${hostip[$1]}

echo "${yellow}- Installing nginx reverse proxy …${reset}"
set_dark

if ssh root@$remote "cat /etc/nginx/nginx.conf" | grep docspell; then
    echo "  - Nginx already setup"
else
    ssh root@$remote "apt-get install -y nginx"

    # export nginx_servername
    # cat $templ | mo > $target/nginx-docspell

    # scp $target/nginx-docspell root@$remote:/etc/nginx/sites-enabled/
    # ssh root@$remote "systemctl reload nginx"
fi

reset_color
