#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
    echo "Mandatory hostname not specified"
    exit 1
fi

source $(dirname $(realpath $0))/../config/global
source $(dirname $(realpath $0))/../scripts/colors

remote=${hostip[$1]}

echo "${yellow}- Setting up os user ${os_user} ...${reset}"
set_dark

if ssh root@$remote "cat /etc/passwd | grep $os_user" 2> /dev/null 1>&2; then
    echo "  - User $os_user already set up."
else
    ssh root@$remote "useradd --home-dir /home/$os_user -m --user-group --shell /bin/bash $os_user"
fi

if [ $(ssh root@$remote "hostname") == $os_hostname ]; then
    echo "  - hostname already set to $os_hostname"
else
    ssh root@$remote "hostnamectl set-hostname $os_hostname || hostname $os_hostname"
fi

reset_color
